-- Sample data for Pest, Disease & Weed Management Guide
-- Adding sample data for Cotton, Paddy, Maize, and Groundnut

-- Insert crops
INSERT INTO public.crops (crop_name, name_en, name_te, scientific_name) VALUES
('Cotton', 'Cotton', 'పంచ', 'Gossypium hirsutum'),
('Paddy', 'Paddy', 'వరి', 'Oryza sativa'),
('Maize', 'Maize', 'మొక్కజొన్న', 'Zea mays'),
('Groundnut', 'Groundnut', 'వేరుశెనగ', 'Arachis hypogaea')
ON CONFLICT DO NOTHING;

-- Get crop IDs
DO $$
DECLARE
  cotton_id UUID;
  paddy_id UUID;
  maize_id UUID;
  groundnut_id UUID;
BEGIN
  SELECT id INTO cotton_id FROM public.crops WHERE name_en = 'Cotton' LIMIT 1;
  SELECT id INTO paddy_id FROM public.crops WHERE name_en = 'Paddy' LIMIT 1;
  SELECT id INTO maize_id FROM public.crops WHERE name_en = 'Maize' LIMIT 1;
  SELECT id INTO groundnut_id FROM public.crops WHERE name_en = 'Groundnut' LIMIT 1;

  -- Insert Cotton Insect Pests
  INSERT INTO public.insect_pests (crop_id, name_en, name_te, scientific_name, identification_en, identification_te, life_cycle_en, life_cycle_te, symptoms_en, symptoms_te, damage_symptoms_en, damage_symptoms_te, economic_threshold_level, ipm_practices_en, ipm_practices_te, chemical_control_en, chemical_control_te, biological_control_en, biological_control_te, preventive_measures_en, preventive_measures_te, is_active, sort_order) VALUES
  (cotton_id, 'Pink Bollworm', 'గులాబీ రంగు కాయతొలిచే పురుగు', 'Pectinophora gossypiella', 'Small pinkish moth with dark spots on wings', 'చిన్న గులాబీ రంగు దుప్పి రెక్కలపై ముద్దులు', 'Eggs laid on squares, larvae feed inside bolls', 'గుడ్లు కాయలపై పెట్టబడతాయి, లార్వా కాయల లోపల తినుతుంది', 'Squares drop, bolls damaged', 'కాయలు రాలిపోతాయి, కాయలు దెబ్బతినేస్తాయి', 'Bolls open prematurely, lint quality reduced', 'కాయలు ముందే తెరుచుకుంటాయి, దారం నాణ్యత తగ్గుతుంది', 'One moth per 5 plants', '5 మొక్కలకు ఒక దుప్పి', 'Use pheromone traps, remove crop residues', 'ఫెరోమోన్ బంధకాలను ఉపయోగించండి, పంట అవశేషాలను తీసివేయండి', 'Emamectin benzoate 5 SG - 80g/acre', 'ఇమామెక్టిన్ బెంజోయేట్ 5 SG - 80గ్రా/ఎకరా', 'Release Trichogramma', 'ట్రైకోగ్రామాను విడుదల చేయండి', 'Early sowing, use resistant varieties', 'ముందుగా వేయండి, నిరోధక రకాలను ఉపయోగించండి', true, 1),
  (cotton_id, 'American Bollworm', 'అమెరికన్ కాయతొలిచే పురుగు', 'Helicoverpa armigera', 'Large brown moth with light brown wings', 'పెద్ద గోధుమ రంగు దుప్పి తేలికపాటి గోధుమ రెక్కలతో', 'Eggs laid singly on leaves and squares', 'గుడ్లు ఆకులు మరియు కాయలపై ఒక్కొక్కటిగా పెట్టబడతాయి', 'Holes in squares and bolls', 'కాయలలో రంధ్రాలు', 'Bolls damaged, lint stained', 'కాయలు దెబ్బతినేస్తాయి, దారం మచ్చలు', 'Two moths per 5 plants', '5 మొక్కలకు రెండు దుప్పులు', 'Use pheromone traps, bird perches', 'ఫెరోమోన్ బంధకాలను ఉపయోగించండి, పక్షుల కర్రలు', 'Chlorantraniliprole 18.5 SC - 60ml/acre', 'క్లోరాంట్రానిలిప్రోల్ 18.5 SC - 60మిల్లీ/ఎకరా', 'Release Trichogramma', 'ట్రైకోగ్రామాను విడుదల చేయండి', 'Crop rotation, destroy crop residues', 'పంట మార్పు, పంట అవశేషాలను నాశనం చేయండి', true, 2),
  (cotton_id, 'Whitefly', 'తెల్ల ఈగ', 'Bemisia tabaci', 'Small white moth-like insects', 'చిన్న తెల్ల దుప్పి వంటి పురుగులు', 'Nymphs and adults suck sap from leaves', 'నింఫ్లు మరియు వయోలు ఆకుల నుండి రసాన్ని పీల్చుతాయి', 'Yellowing of leaves, sooty mold', 'ఆకులు పసుపు రంగులోకి మారతాయి, నల్లని శిలీంధ్రం', 'Leaf curl, reduced yield', 'ఆకులు చుట్టుకుంటాయి, దిగుబలి తగ్గుతుంది', '5 whiteflies per leaf', 'ఒక ఆకుకు 5 తెల్ల ఈగలు', 'Yellow sticky traps, remove alternate hosts', 'పసుపు అంటు బంధకాలు, ఇతర ఆతిథ్య మొక్కలను తీసివేయండి', 'Imidacloprid 17.8 SL - 200ml/acre', 'ఇమిడాక్లోప్రిడ్ 17.8 SL - 200మిల్లీ/ఎకరా', 'Release Encarsia formosa', 'ఎన్కార్సియా ఫార్మోసాను విడుదల చేయండి', 'Avoid excess nitrogen, use reflective mulch', 'అధిక నత్రజనిని నివారించండి, ప్రతిబింబిత మల్చ్ ఉపయోగించండి', true, 3),
  (cotton_id, 'Aphid', 'చిన్న పచ్చిక పురుగు', 'Aphis gossypii', 'Small green pear-shaped insects', 'చిన్న పచ్చిక నారింజ ఆకారంలో పురుగులు', 'Nymphs and adults suck sap', 'నింఫ్లు మరియు వయోలు రసాన్ని పీల్చుతాయి', 'Leaves curl, honeydew secretion', 'ఆకులు చుట్టుకుంటాయి, తేనె స్రావం', 'Sooty mold, stunted growth', 'నల్లని శిలీంధ్రం, ఎదుగుదల ఆగిపోతుంది', '10 aphids per leaf', 'ఒక ఆకుకు 10 చిన్న పచ్చిక పురుగులు', 'Conserve natural enemies, avoid excess nitrogen', 'సహజ శత్రువులను రక్షించండి, అధిక నత్రజనిని నివారించండి', 'Dimethoate 30 EC - 500ml/acre', 'డైమెథోయేట్ 30 EC - 500మిల్లీ/ఎకరా', 'Release lady beetles', 'లేడీ బీటిల్స్ విడుదల చేయండి', 'Remove infested shoots, use neem oil', 'దెబ్బతిన్న కొమ్మలను తీసివేయండి, నీమాయిల్ ఉపయోగించండి', true, 4);

  -- Insert Paddy Insect Pests
  INSERT INTO public.insect_pests (crop_id, name_en, name_te, scientific_name, identification_en, identification_te, life_cycle_en, life_cycle_te, symptoms_en, symptoms_te, damage_symptoms_en, damage_symptoms_te, economic_threshold_level, ipm_practices_en, ipm_practices_te, chemical_control_en, chemical_control_te, biological_control_en, biological_control_te, preventive_measures_en, preventive_measures_te, is_active, sort_order) VALUES
  (paddy_id, 'Stem Borer', 'కాండం తొలిచే పురుగు', 'Scirpophaga incertulas', 'Yellowish moth with brown markings', 'పసుపు దుప్పి గోధుమ గుర్తులతో', 'Eggs laid in masses on leaves, larvae bore into stems', 'గుడ్లు ఆకులపై గుంపులుగా పెట్టబడతాయి, లార్వా కాండాలలోకి తొలిచుతుంది', 'Dead hearts in vegetative stage, white heads at flowering', 'కోసలో చనిపోయిన కాండాలు, పూత సమయంలో తెల్ల తలలు', 'Stems break, chaffy grains', 'కాండాలు విరిగిపోతాయి, పొట్టు ధాన్యాలు', '5% dead hearts', '5% చనిపోయిన కాండాలు', 'Use pheromone traps, clip infested tillers', 'ఫెరోమోన్ బంధకాలను ఉపయోగించండి, దెబ్బతిన్న కొమ్మలను కత్తిరించండి', 'Cartap hydrochloride 4 G - 20kg/acre', 'కార్టాప్ హైడ్రోక్లోరైడ్ 4 G - 20కిలో/ఎకరా', 'Release Trichogramma', 'ట్రైకోగ్రామాను విడుదల చేయండి', 'Early planting, avoid late planting', 'ముందుగా నాటండి, ఆలస్యంగా నాటకుండి', true, 1),
  (paddy_id, 'Leaf Folder', 'ఆకు చుట్టుకునే పురుగు', 'Cnaphalocrocis medinalis', 'Golden brown moth with dark bands', 'బంగారు గోధుమ దుప్పి ముద్దులతో', 'Larvae fold leaves and feed inside', 'లార్వా ఆకులను చుట్టుకుని లోపల తినుతుంది', 'Leaves folded and scraped', 'ఆకులు చుట్టుకుని గీతలు', 'Reduced photosynthesis, white patches', 'కిరణజన్యాసంవిధానం తగ్గుతుంది, తెల్ల మచ్చలు', 'One larva per hill', 'ఒక దిమ్మకు ఒక లార్వా', 'Use pheromone traps, maintain water level', 'ఫెరోమోన్ బంధకాలను ఉపయోగించండి, నీటి స్థాయిని నిర్వహించండి', 'Chlorpyrifos 20 EC - 1L/acre', 'క్లోర్పైరిఫాస్ 20 EC - 1లీ/ఎకరా', 'Release Trichogramma', 'ట్రైకోగ్రామాను విడుదల చేయండి', 'Avoid excess nitrogen, balanced fertilization', 'అధిక నత్రజనిని నివారించండి, సమతుల్య ఎరువులు', true, 2),
  (paddy_id, 'Brown Plant Hopper', 'గోధుమ మొక్క గొంతుకునే పురుగు', 'Nilaparvata lugens', 'Small brown hopper', 'చిన్న గోధుమ గొంతుకునే పురుగు', 'Nymphs and adults suck sap from stems', 'నింఫ్లు మరియు వయోలు కాండాల నుండి రసాన్ని పీల్చుతాయి', 'Hopper burn, yellowing of leaves', 'గొంతుకునే దహనం, ఆకులు పసుపు రంగులోకి మారతాయి', 'Plants dry up, circular patches', 'మొక్కలు ఎండిపోతాయి, వృత్తాకార మచ్చలు', '5 hoppers per hill', 'ఒక దిమ్మకు 5 గొంతుకునే పురుగులు', 'Drain water periodically, use resistant varieties', 'నీటిని క్రమం తప్పకుండా ఖాళీ చేయండి, నిరోధక రకాలను ఉపయోగించండి', 'Imidacloprid 17.8 SL - 200ml/acre', 'ఇమిడాక్లోప్రిడ్ 17.8 SL - 200మిల్లీ/ఎకరా', 'Release mirid bugs', 'మిరిడ్ బగ్స్ విడుదల చేయండి', 'Avoid late planting, balanced fertilization', 'ఆలస్యంగా నాటకుండి, సమతుల్య ఎరువులు', true, 3);

  -- Insert Maize Insect Pests
  INSERT INTO public.insect_pests (crop_id, name_en, name_te, scientific_name, identification_en, identification_te, life_cycle_en, life_cycle_te, symptoms_en, symptoms_te, damage_symptoms_en, damage_symptoms_te, economic_threshold_level, ipm_practices_en, ipm_practices_te, chemical_control_en, chemical_control_te, biological_control_en, biological_control_te, preventive_measures_en, preventive_measures_te, is_active, sort_order) VALUES
  (maize_id, 'Fall Armyworm', 'పడిపోయే సైన్యం పురుగు', 'Spodoptera frugiperda', 'Brown moth with mottled wings', 'గోధుమ దుప్పి చిట్కాలతో', 'Larvae feed on whorl and tassel', 'లార్వా విసనాల మరియు పూలపై తినుతుంది', 'Shot holes in leaves, frass in whorl', 'ఆకులలో రంధ్రాలు, విసనాలలో పేడ', 'Defoliation, poor cob formation', 'ఆకులు రాలిపోతాయి, కాబ్ ఏర్పాటు చెడుతుంది', '5% plants with egg masses', '5% మొక్కలు గుడ్ల గుంపులతో', 'Hand pick egg masses, use pheromone traps', 'గుడ్ల గుంపులను చేతితో తీయండి, ఫెరోమోన్ బంధకాలను ఉపయోగించండి', 'Emamectin benzoate 5 SG - 80g/acre', 'ఇమామెక్టిన్ బెంజోయేట్ 5 SG - 80గ్రా/ఎకరా', 'Release Trichogramma', 'ట్రైకోగ్రామాను విడుదల చేయండి', 'Early planting, push-pull technology', 'ముందుగా నాటండి, పుష్-పుల్ సాంకేతికత', true, 1),
  (maize_id, 'Stem Borer', 'కాండం తొలిచే పురుగు', 'Chilo partellus', 'Yellowish moth with dark spots', 'పసుపు దుప్పి ముద్దులతో', 'Larvae bore into stem', 'లార్వా కాండంలోకి తొలిచుతుంది', 'Dead hearts, broken stems', 'చనిపోయిన కాండాలు, విరిగిన కాండాలు', 'Lodging, poor grain filling', 'మొక్కలు పడిపోతాయి, ధాన్యం నింపకపోవడం', '10% dead hearts', '10% చనిపోయిన కాండాలు', 'Use pheromone traps, destroy crop residues', 'ఫెరోమోన్ బంధకాలను ఉపయోగించండి, పంట అవశేషాలను నాశనం చేయండి', 'Chlorantraniliprole 18.5 SC - 60ml/acre', 'క్లోరాంట్రానిలిప్రోల్ 18.5 SC - 60మిల్లీ/ఎకరా', 'Release Trichogramma', 'ట్రైకోగ్రామాను విడుదల చేయండి', 'Crop rotation, use resistant varieties', 'పంట మార్పు, నిరోధక రకాలను ఉపయోగించండి', true, 2);

  -- Insert Groundnut Insect Pests
  INSERT INTO public.insect_pests (crop_id, name_en, name_te, scientific_name, identification_en, identification_te, life_cycle_en, life_cycle_te, symptoms_en, symptoms_te, damage_symptoms_en, damage_symptoms_te, economic_threshold_level, ipm_practices_en, ipm_practices_te, chemical_control_en, chemical_control_te, biological_control_en, biological_control_te, preventive_measures_en, preventive_measures_te, is_active, sort_order) VALUES
  (groundnut_id, 'Leaf Miner', 'ఆకు గని పురుగు', 'Aproaerema modicella', 'Small moth with silvery wings', 'చిన్న దుప్పి వెండి రెక్కలతో', 'Larvae mine between leaf surfaces', 'లార్వా ఆకు పొరల మధ్య గని తిరుగుతుంది', 'Silvery blotches on leaves', 'ఆకులపై వెండి మచ్చలు', 'Reduced photosynthesis, defoliation', 'కిరణజన్యాసంవిధానం తగ్గుతుంది, ఆకులు రాలిపోతాయి', '10% leaves with mines', '10% ఆకులు గన్లతో', 'Remove infested leaves, use pheromone traps', 'దెబ్బతిన్న ఆకులను తీసివేయండి, ఫెరోమోన్ బంధకాలను ఉపయోగించండి', 'Quinalphos 25 EC - 1L/acre', 'క్వినాల్ఫాస్ 25 EC - 1లీ/ఎకరా', 'Release Trichogramma', 'ట్రైకోగ్రామాను విడుదల చేయండి', 'Early sowing, crop rotation', 'ముందుగా వేయండి, పంట మార్పు', true, 1),
  (groundnut_id, 'Aphids', 'చిన్న పచ్చిక పురుగులు', 'Aphis craccivora', 'Small green insects', 'చిన్న పచ్చిక పురుగులు', 'Nymphs and adults suck sap', 'నింఫ్లు మరియు వయోలు రసాన్ని పీల్చుతాయి', 'Leaves curl, honeydew secretion', 'ఆకులు చుట్టుకుంటాయి, తేనె స్రావం', 'Sooty mold, stunted growth', 'నల్లని శిలీంధ్రం, ఎదుగుదల ఆగిపోతుంది', '15 aphids per leaf', 'ఒక ఆకుకు 15 చిన్న పచ్చిక పురుగులు', 'Conserve natural enemies, spray neem oil', 'సహజ శత్రువులను రక్షించండి, నీమాయిల్ స్ప్రే చేయండి', 'Dimethoate 30 EC - 500ml/acre', 'డైమెథోయేట్ 30 EC - 500మిల్లీ/ఎకరా', 'Release lady beetles', 'లేడీ బీటిల్స్ విడుదల చేయండి', 'Avoid excess nitrogen, use resistant varieties', 'అధిక నత్రజనిని నివారించండి, నిరోధక రకాలను ఉపయోగించండి', true, 2);

  -- Insert Cotton Diseases
  INSERT INTO public.diseases (crop_id, name_en, name_te, scientific_name, symptoms_en, symptoms_te, favourable_conditions_en, favourable_conditions_te, disease_cycle_en, disease_cycle_te, integrated_management_en, integrated_management_te, chemical_control_en, chemical_control_te, biological_control_en, biological_control_te, preventive_measures_en, preventive_measures_te, is_active, sort_order) VALUES
  (cotton_id, 'Bacterial Blight', 'బాక్టీరియల్ బ్లైట్', 'Xanthomonas axonopodis', 'Water-soaked lesions on leaves, bolls', 'ఆకులు, కాయలపై నీటి మచ్చలు', 'High humidity, warm temperature', 'అధిక తేమ, వెచ్చని ఉష్ణోగ్రహం', 'Bacteria enters through wounds', 'బాక్టీరియా గాయాల ద్వారా ప్రవేశిస్తుంది', 'Use resistant varieties, crop rotation', 'నిరోధక రకాలను ఉపయోగించండి, పంట మార్పు', 'Copper oxychloride 3g/L', 'కాపర్ ఆక్సీక్లోరైడ్ 3గ్రా/లీ', 'Use bacteriophages', 'బాక్టీరియోఫేజెస్ ఉపయోగించండి', 'Use disease-free seeds, avoid overhead irrigation', 'వ్యాధి లేని విత్తనాలను ఉపయోగించండి, పైన నీటిపారుదల నివారించండి', true, 1),
  (cotton_id, 'Alternaria Leaf Spot', 'ఆల్టర్నేరియా ఆకు మచ్చ', 'Alternaria macrospora', 'Brown circular spots on leaves', 'ఆకులపై గోధుమ వృత్తాకార మచ్చలు', 'Cool wet weather', 'చల్లని తడి వాతావరణం', 'Fungus survives in crop debris', 'శిలీంధ్రం పంట అవశేషాలలో జీవిస్తుంది', 'Remove infected leaves, use fungicides', 'దెబ్బతిన్న ఆకులను తీసివేయండి, ఫంగిసైడ్లు ఉపయోగించండి', 'Mancozeb 2g/L', 'మాంకోజెబ్ 2గ్రా/లీ', 'Use Trichoderma', 'ట్రైకోడెర్మా ఉపయోగించండి', 'Crop rotation, balanced fertilization', 'పంట మార్పు, సమతుల్య ఎరువులు', true, 2);

  -- Insert Paddy Diseases
  INSERT INTO public.diseases (crop_id, name_en, name_te, scientific_name, symptoms_en, symptoms_te, favourable_conditions_en, favourable_conditions_te, disease_cycle_en, disease_cycle_te, integrated_management_en, integrated_management_te, chemical_control_en, chemical_control_te, biological_control_en, biological_control_te, preventive_measures_en, preventive_measures_te, is_active, sort_order) VALUES
  (paddy_id, 'Blast', 'బ్లాస్ట్', 'Pyricularia oryzae', 'Diamond-shaped spots on leaves', 'ఆకులపై వజ్రాకార మచ్చలు', 'High humidity, cool nights', 'అధిక తేమ, చల్లని రాత్రులు', 'Fungus survives in crop residues', 'శిలీంధ్రం పంట అవశేషాలలో జీవిస్తుంది', 'Use resistant varieties, avoid excess nitrogen', 'నిరోధక రకాలను ఉపయోగించండి, అధిక నత్రజనిని నివారించండి', 'Tricyclazole 0.6g/L', 'ట్రైసైక్లాజోల్ 0.6గ్రా/లీ', 'Use Trichoderma', 'ట్రైకోడెర్మా ఉపయోగించండి', 'Use disease-free seeds, balanced fertilization', 'వ్యాధి లేని విత్తనాలను ఉపయోగించండి, సమతుల్య ఎరువులు', true, 1),
  (paddy_id, 'Sheath Blight', 'చేను బ్లైట్', 'Rhizoctonia solani', 'Oval lesions on sheath', 'చేనుపై అండాకార మచ్చలు', 'High humidity, dense planting', 'అధిక తేమ, దట్టమైన నాటడం', 'Fungus survives in soil', 'శిలీంధ్రం నేలలో జీవిస్తుంది', 'Avoid dense planting, use fungicides', 'దట్టమైన నాటడం నివారించండి, ఫంగిసైడ్లు ఉపయోగించండి', 'Validamycin 2ml/L', 'వాలిడామైసిన్ 2మిల్లీ/లీ', 'Use Trichoderma', 'ట్రైకోడెర్మా ఉపయోగించండి', 'Optimum spacing, balanced fertilization', 'సరైన దూరం, సమతుల్య ఎరువులు', true, 2);

  -- Insert Maize Diseases
  INSERT INTO public.diseases (crop_id, name_en, name_te, scientific_name, symptoms_en, symptoms_te, favourable_conditions_en, favourable_conditions_te, disease_cycle_en, disease_cycle_te, integrated_management_en, integrated_management_te, chemical_control_en, chemical_control_te, biological_control_en, biological_control_te, preventive_measures_en, preventive_measures_te, is_active, sort_order) VALUES
  (maize_id, 'Turcicum Leaf Blight', 'టర్సికం ఆకు బ్లైట్', 'Exserohilum turcicum', 'Long elliptical lesions on leaves', 'ఆకులపై పొడవైన దీర్ఘవృత్తాకార మచ్చలు', 'Cool wet weather', 'చల్లని తడి వాతావరణం', 'Fungus survives in crop debris', 'శిలీంధ్రం పంట అవశేషాలలో జీవిస్తుంది', 'Use resistant varieties, crop rotation', 'నిరోధక రకాలను ఉపయోగించండి, పంట మార్పు', 'Mancozeb 2g/L', 'మాంకోజెబ్ 2గ్రా/లీ', 'Use Trichoderma', 'ట్రైకోడెర్మా ఉపయోగించండి', 'Early planting, avoid late planting', 'ముందుగా నాటండి, ఆలస్యంగా నాటకుండి', true, 1);

  -- Insert Groundnut Diseases
  INSERT INTO public.diseases (crop_id, name_en, name_te, scientific_name, symptoms_en, symptoms_te, favourable_conditions_en, favourable_conditions_te, disease_cycle_en, disease_cycle_te, integrated_management_en, integrated_management_te, chemical_control_en, chemical_control_te, biological_control_en, biological_control_te, preventive_measures_en, preventive_measures_te, is_active, sort_order) VALUES
  (groundnut_id, 'Tikka Leaf Spot', 'టిక్కా ఆకు మచ్చ', 'Cercospora arachidicola', 'Circular spots on leaves', 'ఆకులపై వృత్తాకార మచ్చలు', 'Warm humid weather', 'వెచ్చని తేమ వాతావరణం', 'Fungus survives in crop residues', 'శిలీంధ్రం పంట అవశేషాలలో జీవిస్తుంది', 'Use resistant varieties, crop rotation', 'నిరోధక రకాలను ఉపయోగించండి, పంట మార్పు', 'Chlorothalonil 2g/L', 'క్లోరోథలోనిల్ 2గ్రా/లీ', 'Use Trichoderma', 'ట్రైకోడెర్మా ఉపయోగించండి', 'Use disease-free seeds, avoid late sowing', 'వ్యాధి లేని విత్తనాలను ఉపయోగించండి, ఆలస్యంగా వేయకుండి', true, 1);

  -- Insert Cotton Weeds
  INSERT INTO public.weeds (crop_id, name_en, name_te, scientific_name, weed_type, description_en, description_te, is_active, sort_order) VALUES
  (cotton_id, 'Parthenium', 'పార్థేనియం', 'Parthenium hysterophorus', 'broadleaf', 'Invasive weed causing allergies', 'అలర్జీలను కలిగించే ఆక్రమణ కలుపు మొక్క', true, 1),
  (cotton_id, 'Cynodon', 'గడ్డి', 'Cynodon dactylon', 'grass', 'Perennial grass weed', 'బహువార్షిక గడ్డి కలుపు మొక్క', true, 2);

  -- Insert Paddy Weeds
  INSERT INTO public.weeds (crop_id, name_en, name_te, scientific_name, weed_type, description_en, description_te, is_active, sort_order) VALUES
  (paddy_id, 'Echinochloa', 'గడ్డి', 'Echinochloa crus-galli', 'grass', 'Major grass weed in paddy', 'వరిలో ప్రధాన గడ్డి కలుపు మొక్క', true, 1),
  (paddy_id, 'Cyperus', 'నగర్ గడ్డి', 'Cyperus rotundus', 'sedge', 'Perennial sedge weed', 'బహువార్షిక సెడ్జ్ కలుపు మొక్క', true, 2);

  -- Insert Maize Weeds
  INSERT INTO public.weeds (crop_id, name_en, name_te, scientific_name, weed_type, description_en, description_te, is_active, sort_order) VALUES
  (maize_id, 'Amaranthus', 'తోటకూర', 'Amaranthus viridis', 'broadleaf', 'Common broadleaf weed', 'సాధారణ బ్రాడ్లీఫ్ కలుపు మొక్క', true, 1),
  (maize_id, 'Eleusine', 'గడ్డి', 'Eleusine indica', 'grass', 'Annual grass weed', 'వార్షిక గడ్డి కలుపు మొక్క', true, 2);

  -- Insert Groundnut Weeds
  INSERT INTO public.weeds (crop_id, name_en, name_te, scientific_name, weed_type, description_en, description_te, is_active, sort_order) VALUES
  (groundnut_id, 'Cassia', 'తామర', 'Cassia tora', 'broadleaf', 'Common broadleaf weed', 'సాధారణ బ్రాడ్లీఫ్ కలుపు మొక్క', true, 1),
  (groundnut_id, 'Digitaria', 'గడ్డి', 'Digitaria sanguinalis', 'grass', 'Annual grass weed', 'వార్షిక గడ్డి కలుపు మొక్క', true, 2);

END $$;
